env:
  browser: true
  es6: true
  jquery: true
extends:
  - 'eslint:recommended'
  - wordpress
globals:
  wp: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  yoda: 'off'
  space-in-parens: 'off'
  vars-on-top: 'off'
