name: WP Job Openings Coding Standards based Formatting

on:
  push:
    branches: [ dev-branch, v3-dev-branch ]
    paths:
      - 'phpcs.xml'
      - '**.php'
  pull_request:
    branches: [ dev-branch, v3-dev-branch ]
    paths:
      - 'phpcs.xml'
      - '**.php'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phpcbf
      run: composer run-script phpcbfx

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "IMPROVE: Code formatting based on phpcs"
